version: '3.7'
services:
  pn_database:
    build:
      context: .
      dockerfile: ./backend/config/docker/database.dockerfile
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    container_name: pn_database
    hostname: pn_database
    environment: 
      MYSQL_ROOT_PASSWORD: "PyNanceV3"
      MYSQL_DATABASE: "PYNANCE"
    volumes:
      - ./backend/config/docker/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    networks:
      - pynance
  
  pn_dashboard:
    container_name: pn_dashboard
    hostname: pn_dashboard  
    build:
      context: .
      dockerfile: ./backend/config/docker/dashboard.dockerfile
    environment:
      FLASK_ENV: production
      FLASK_APP: "webserver.py:create_server()"
      FLASK_RUN_HOST: 0.0.0.0
    depends_on:
      - pn_database
    links:
      - pn_database
    networks:
      - pynance
    restart: on-failure
  
  pn_listener:
    container_name: pn_listener
    build:
      context: .
      dockerfile: ./backend/config/docker/listener.dockerfile
    depends_on: 
      - pn_database
      - pn_dashboard
    links:
      - pn_database
      - pn_dashboard
    networks:
      - pynance
    restart: always

  nginx:
    container_name: nginx
    image: nginx:stable
    volumes:
      - ./backend/config/docker/nginx.conf:/etc/nginx/nginx.conf
    depends_on: 
      - pn_dashboard
    links:
      - pn_dashboard
    ports:
      - 1337:5000
    networks:
      - pynance
    restart:
      always
  
networks:
  pynance:
